from scripts.entities.traps.traps.shared.spike import Spike
from scripts.entities.traps.traps.shared.rubble import Rubble
from scripts.entities.traps.traps.shared.spike_poisoned import Spike_Poisoned
from scripts.entities.traps.traps.shared.spike_pit import Spike_Pit
from scripts.entities.traps.traps.shared.fire_trap import Fire_Trap
from scripts.entities.traps.environment.lava import Lava
from scripts.entities.traps.environment.water import Water
from scripts.entities.traps.environment.ice import Ice
from scripts.entities.traps.traps.shared.spider_web import Spider_Web
from scripts.entities.traps.traps.ancient_tomb.arrow_trap import Arrow_Trap