
from scripts.entities.items.loot.passive.lantern import Lantern
from scripts.entities.items.loot.passive.passive_loot import Passive_Loot
from scripts.entities.items.loot.passive.echo_sigil import Echo_Sigil
from scripts.entities.items.loot.passive.recipe_scroll import Recipe_Scroll
from scripts.entities.items.loot.loot_types_handler import Loot_Types_Handler

from scripts.engine.keys.keys import keys


class Passive_Loot_Handler(Loot_Types_Handler):
    def __init__(self, game):
        super().__init__(game)

        self.loot_map = {
            keys.lantern: Lantern,
            keys.echo_sigil: Echo_Sigil,
            keys.recipe_scroll: Recipe_Scroll,
            keys.anchor_stone : Passive_Loot,
            keys.magnet : Passive_Loot,
            keys.strength_totem : Passive_Loot,
            keys.power_totem : Passive_Loot,
            keys.muffled_boots : Passive_Loot,
            keys.halo : Passive_Loot,
            keys.faith_pendant : Passive_Loot,
            keys.lucky_charm : Passive_Loot,
        }


    def Get_Loot_Values(self):
        loot_types_cost = {
            # Lantern – Sets the player's light radius to 7 (passive light).
            keys.lantern: 10,

            # Echo Sigil – Increases the activations of items by 1.
            keys.echo_sigil: 45,

            # Recipe Scroll – Increases potion strength by +1, works similar to Echo Sigil.
            keys.recipe_scroll: 30,

            # Anchor Stone – Prevents the player from being pushed by traps or enemies.
            keys.anchor_stone: 20,

            # Magnet – Automatically picks up nearby items.
            keys.magnet: 10,

            # Totem of Strength – Increases the player's strength.
            keys.strength_totem: 20,

            # Totem of Power – Increases rune power; stacks with multiple totems.
            keys.power_totem: 20,

            # Muffled Boots – Reduces the noise generated by movement.
            keys.muffled_boots: 30,

            # Lucky Charm - Improves player luck
            keys.lucky_charm: 25,

            # Halo – Gives a 1/10 chance to negate incoming damage.
            keys.halo: 40,

            # Faith Pendant – (Add description here if you want one.)
            # keys.faith_pendant: 40,

            # Lucky Charm – Improves luck
            keys.lucky_charm: 25,
        }


        return loot_types_cost





