from scripts.engine.keys.enemy import Enemy as enemy_keys
from scripts.entities.moving_entities.enemies.attribute_distributor.enemy_base_state import Enemy_Base_State

ELEMENTAL_STATS = {
    enemy_keys.fire_spirit: Enemy_Base_State(
        health=40,
        souls=20,
        size=(32, 32),
        max_weapon_charge=0.8,
        strength=4,
        speed=4,
        agility=4,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.short_range,
        sub_category=enemy_keys.elemental,
        ability=None,
        path_finding_strategy='ignore_lava',
        idle_animation=3,
        run_animation=3,
        attack_animation=3,
    ),

    enemy_keys.ice_spirit: Enemy_Base_State(
        health=50,
        souls=20,
        size=(32, 32),
        max_weapon_charge=0.9,
        strength=7,
        speed=3,
        agility=3,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.medium_range,
        sub_category=enemy_keys.elemental,
        ability=None,
        idle_animation=3,
        run_animation=3,
        attack_animation=3,
    ),

    enemy_keys.earth_elemental: Enemy_Base_State(
        health=40,
        souls=30,
        size=(48, 48),
        max_weapon_charge=2.0,
        strength=5,
        speed=2,
        agility=4,
        intelligence=7,
        stamina=2,
        behavior=enemy_keys.hit_and_run,
        sub_category=enemy_keys.elemental,
        ability=enemy_keys.invisibility,
        idle_animation=3,
        run_animation=3,
        attack_animation=3,
    ),

    enemy_keys.electric_elemental: Enemy_Base_State(
        health=50,
        souls=30,
        size=(32, 32),
        max_weapon_charge=3.0,
        strength=4,
        speed=2,
        agility=3,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.medium_range,
        sub_category=enemy_keys.elemental,
        ability=None,
        idle_animation=3,
        run_animation=3,
        attack_animation=3,
    ),

    enemy_keys.poison_elemental: Enemy_Base_State(
        health=20,
        souls=10,
        size=(32, 32),
        max_weapon_charge=0.1,
        strength=4,
        speed=4,
        agility=3,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.elemental,
        ability=None,
        idle_animation=3,
        run_animation=3,
        attack_animation=3,
    ),
}