from scripts.engine.keys.enemy import Enemy as enemy_keys
from scripts.entities.moving_entities.enemies.attribute_distributor.enemy_base_state import Enemy_Base_State

SKELETON_STATS = {
    enemy_keys.skeleton_warrior: Enemy_Base_State(
        health=70,
        souls=10,
        size=(32, 32),
        strength=3,
        speed=3,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.skeleton,
        ability=None,
        idle_animation=0,
        run_animation=6,
        attack_animation=6,
    ),

    enemy_keys.skeleton_ranger: Enemy_Base_State(
        health=40,
        souls=15,
        size=(32, 32),
        strength=2,
        speed=4,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.long_range,
        sub_category=enemy_keys.skeleton,
        ability=enemy_keys.run_away,
        idle_animation=0,
        run_animation=3,
        attack_animation=3,
    ),

    enemy_keys.skeleton_cleric: Enemy_Base_State(
        health=40,
        souls=20,
        size=(32, 32),
        strength=1,
        speed=2,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.medium_range,
        sub_category=enemy_keys.skeleton,
        ability=enemy_keys.healer,
        idle_animation=0,
        run_animation=6,
        attack_animation=6,
    ),

    enemy_keys.skeleton_bell_toller: Enemy_Base_State(
        health=60,
        souls=15,
        size=(32, 32),
        strength=3,
        speed=3,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.short_range,
        sub_category=enemy_keys.skeleton,
        ability=None,
        idle_animation=0,
        run_animation=6,
        attack_animation=6,
    ),

    enemy_keys.skeleton_undertaker: Enemy_Base_State(
        health=110,
        souls=40,
        size=(32, 32),
        strength=5,
        speed=2,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.short_range,
        sub_category=enemy_keys.skeleton,
        ability=enemy_keys.bone_ressurector,
        idle_animation=0,
        run_animation=6,
        attack_animation=6,
    ),

    enemy_keys.skeleton_guardian: Enemy_Base_State(
        health=120,
        souls=15,
        size=(32, 32),
        strength=4,
        speed=1,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.skeleton,
        ability=enemy_keys.invulnerable,
        idle_animation=0,
        run_animation=6,
        attack_animation=6,
    ),

    enemy_keys.skeleton_warlock: Enemy_Base_State(
        health=40,
        souls=40,
        size=(32, 32),
        strength=1,
        speed=1,
        agility=2,
        intelligence=5,
        stamina=2,
        behavior=enemy_keys.medium_range,
        sub_category=enemy_keys.skeleton,
        ability=None,
        idle_animation=0,
        run_animation=3,
        attack_animation=4,
    ),

    enemy_keys.wight_king: Enemy_Base_State(
        health=200,
        souls=55,
        size=(40, 40),
        strength=6,
        speed=4,
        agility=6,
        intelligence=5,
        stamina=5,
        behavior=enemy_keys.hit_and_run,
        sub_category=enemy_keys.skeleton,
        ability=enemy_keys.dash,
        idle_animation=0,
        run_animation=4,
        attack_animation=4,
    ),

    enemy_keys.skeleton_banner_bearer: Enemy_Base_State(
        health=50,
        souls=15,
        size=(32, 32),
        strength=1,
        speed=2,
        agility=2,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.medium_range,
        sub_category=enemy_keys.skeleton,
        ability=enemy_keys.rally,
        idle_animation=0,
        run_animation=6,
        attack_animation=6,
    ),
}