from scripts.engine.keys.enemy import Enemy as enemy_keys
from scripts.entities.moving_entities.enemies.attribute_distributor.enemy_base_state import Enemy_Base_State

VOID_SPAWN_STATS = {
    enemy_keys.phantom: Enemy_Base_State(
        health=20,
        souls=30,
        size=(32, 32),
        strength=5,
        speed=6,
        agility=7,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.void_spawn,
        ability=None,
        idle_animation=4,
        run_animation=4,
        attack_animation=5,
    ),

    enemy_keys.wraith: Enemy_Base_State(
        health=50,
        souls=25,
        size=(32, 32),
        strength=3,
        speed=4,
        agility=6,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.void_spawn,
        ability=None,
        idle_animation=4,
        run_animation=4,
        attack_animation=5,
    ),

    enemy_keys.shade: Enemy_Base_State(
        health=30,
        souls=20,
        size=(32, 32),
        strength=5,
        speed=2,
        agility=5,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.void_spawn,
        ability=None,
        idle_animation=4,
        run_animation=4,
        attack_animation=5,
    ),

    enemy_keys.rift_stalker: Enemy_Base_State(
        health=50,
        souls=20,
        size=(32, 32),
        strength=3,
        speed=1,
        agility=7,
        intelligence=2,
        stamina=2,
        behavior=enemy_keys.direct_attack,
        sub_category=enemy_keys.void_spawn,
        ability=None,
        idle_animation=4,
        run_animation=4,
        attack_animation=5,
    ),
}