from scripts.entities.moving_entities.effects.effects_handler import Status_Effect_Handler
from scripts.entities.moving_entities.effects.player.silence import Silence
from scripts.entities.moving_entities.effects.player.soul_drained import Soul_Drained
from scripts.entities.moving_entities.effects.souls.arcane_conduit import Arcane_Conduit
from scripts.entities.moving_entities.effects.souls.arcane_hunger import Arcane_Hunger
from scripts.entities.moving_entities.effects.player.magnet import Magnet
from scripts.entities.moving_entities.effects.player.halo import Halo
from scripts.entities.moving_entities.effects.player.curse.blood_tomb import Blood_Tomb
from scripts.entities.moving_entities.effects.player.player_movement_invunerable import Player_Movement_Invunerable
from scripts.entities.moving_entities.effects.player.power import Power
from scripts.entities.moving_entities.effects.player.curse.demonic_bargain import Demonic_Bargain
from scripts.entities.moving_entities.effects.player.curse.temptress_embrace import Temptress_Embrace
from scripts.entities.moving_entities.effects.player.curse.forsaken_grimoire import Forsaken_Grimoire
from scripts.entities.moving_entities.effects.player.curse.black_coin import Black_Coin
from scripts.entities.moving_entities.effects.souls.increase_souls import Increase_Souls
from scripts.entities.moving_entities.effects.player.luck import Luck
from scripts.entities.moving_entities.effects.player.curse.blood_ring import Blood_Ring