from scripts.entities.moving_entities.effects.poison.poison import Poison
from scripts.entities.moving_entities.effects.frozen.frozen import Frozen
from scripts.entities.moving_entities.effects.water.wet import Wet
from scripts.entities.moving_entities.effects.healing.regen import Regen
from scripts.entities.moving_entities.effects.movement.speed import Speed
from scripts.entities.moving_entities.effects.general.strength import Increase_Strength
from scripts.entities.moving_entities.effects.general.weakness import Weakness
from scripts.entities.moving_entities.effects.general.invisibility import Invisibility
from scripts.entities.moving_entities.effects.fire.fire_resistance import Fire_Resistance
from scripts.entities.moving_entities.effects.fire.fire import Fire
from scripts.entities.moving_entities.effects.frozen.frozen_resistance import Frozen_Resistance
from scripts.entities.moving_entities.effects.poison.poison_resistance import Poison_Resistance
from scripts.entities.moving_entities.effects.movement.snare import Snare
from scripts.entities.moving_entities.effects.movement.anchor import Anchor
from scripts.entities.moving_entities.effects.healing.healing import Healing
from scripts.entities.moving_entities.effects.healing.increase_max_health import Increase_Max_Health
from scripts.entities.moving_entities.effects.movement.slow import Slow
from scripts.entities.moving_entities.effects.healing.vampiric import Vampiric
from scripts.entities.moving_entities.effects.damage.invulnerable import Invulnerable
from scripts.entities.moving_entities.effects.damage.vulnerable import Vulnerable
from scripts.entities.moving_entities.effects.damage.thorns import Thorns
from scripts.entities.moving_entities.effects.electric.eletric import Electric
from scripts.entities.moving_entities.effects.electric.electric_resistance import Electric_Resistance
from scripts.entities.moving_entities.effects.electric.electric_charge import Electric_Charge
from scripts.entities.moving_entities.effects.general.resistance import Resistance
from scripts.entities.moving_entities.effects.general.noisy_attacker import Noisy_Attacker